# SPDX-License-Identifier: GPL-3.0-or-later
"""Rendering the mission list into docs/missions/: an overview checklist and one page per level.

Research: docs/guides/research-workflow.md#missions
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

from coney_tools import natives
from coney_tools.config import find_repo_root
from coney_tools.missions import GROUPS, STATUSES, Coverage, Mission, MissionList, coverage, load

PAGES_DIR = Path("docs/missions")
WIDTH = 120  # the docs' line length (.markdownlint.yaml, MD013)
GENERATED = "<!-- Generated by `coney-tools missions render` from research/missions.yaml. Do not edit. -->"
NO_COVERAGE = Coverage(0, 0, 0, 0, {})


def _wrap(text: str, indent: str = "", first: str = "") -> list[str]:
    """`text` as lines of at most WIDTH characters; blank-line-separated paragraphs stay separate.

    `first` starts the first line of each paragraph (a bullet) and `indent` the others.
    """
    lines: list[str] = []
    for number, paragraph in enumerate(p for p in text.strip().split("\n\n")):
        if number:
            lines.append("")
        lines += textwrap.wrap(
            " ".join(paragraph.split()),
            WIDTH,
            initial_indent=first or indent,
            subsequent_indent=indent,
            break_long_words=False,
            break_on_hyphens=False,
        )
    return lines


def label(status: str) -> str:
    """A status as its icon and label."""
    icon, name, _meaning = STATUSES[status]
    return f"{icon} {name}"


def _cell(text: str) -> str:
    """Text safe inside a table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def _bindings_cell(cover: Coverage) -> str:
    """`new in Coney / new` for the overview, or a dash when the level has none."""
    return f"{cover.new_done} of {cover.new}" if cover.new else "-"


def _intro_table(mission: Mission) -> list[str]:
    """The facts at the top of a mission page."""
    return [
        "| | |",
        "| --- | --- |",
        f"| Status | {label(mission.status)} |",
        f"| Level | `{mission.name}` ({mission.slot}) |",
        f"| Checkpoints | {mission.built()} of {len(mission.checkpoints)} built, {mission.approved()} approved |",
    ]


def _needs(mission: Mission, cover: Coverage) -> list[str]:
    """The "What it needs" section: the bindings' numbers by family and the research pages."""
    out = ["", "## What it needs {#needs}", ""]
    story = f"../references/bindings/{'mission1.md' if mission.level == 99 else 'story.md#' + mission.name}"
    if mission.level == 99:
        text = (
            f"Its scripts can call {cover.total} script bindings, all new to the story; {cover.new_done} are"
            f" implemented in Coney and {cover.new_traced} are traced."
        )
    else:
        text = (
            f"Its scripts can call {cover.total} script bindings. {cover.new} of them are new, which no earlier level"
            f" of the story calls: {cover.new_done} are implemented in Coney and {cover.new_traced} are traced."
        )
    out += _wrap(f"{text} The full list is on [the coverage page]({story}).")
    if cover.families:
        out += ["", "| Family | New bindings | In Coney |", "| --- | --- | --- |"]
        for category, (count, done) in cover.families.items():
            title = natives.CATEGORIES[category][0]
            out.append(f"| [{title}](../references/bindings/{category}.md) | {count} | {done} |")
    if mission.research:
        out += ["", "Research:", ""]
        out += [f"- [{link.title}](../{link.path})" for link in mission.research]
    return out


def _checkpoints(mission: Mission) -> list[str]:
    """The checkpoint checklist."""
    out = ["", "## Checkpoints {#checkpoints}", "", "| # | Status | Note |", "| --- | --- | --- |"]
    out += [f"| {c.number} | {label(c.status)} | {_cell(c.note) or '-'} |" for c in mission.checkpoints]
    return out


def _run(mission: Mission) -> list[str]:
    """How to play the level and run its test."""
    count = len(mission.checkpoints)
    out = ["", "## Run it in Coney {#run}", ""]
    out += _wrap(
        "With your own disc ([Playing a level](../guides/building.md#playing-a-level)); `--checkpoint` picks "
        f"where it starts, 1 to {count}:"
    )
    out += ["", "```text", f"coney --disc /path/to/disc --play-level {mission.name} --checkpoint 1", "```"]
    if mission.test:
        out += [
            "",
            "Its disc test (needs `CONEY_DISC`; [Building](../guides/building.md)):",
            "",
            "```text",
            mission.test,
        ]
        out += ["```"]
    return out


def mission_page(mission: Mission, cover: Coverage) -> str:
    """One level's page."""
    out = [GENERATED, "", f"# {mission.title}", ""]
    out += _wrap(mission.summary)
    out += ["", *_intro_table(mission)]
    out += _checkpoints(mission)
    out += _needs(mission, cover)
    if mission.issues:
        out += ["", "## Known issues {#issues}", ""]
        for issue in mission.issues:
            out += _wrap(issue, indent="  ", first="- ")
    out += _run(mission)
    if mission.questions:
        out += ["", "## Open questions {#questions}", ""]
        for question in mission.questions:
            out += _wrap(question, indent="  ", first="- ")
    if mission.notes:
        out += ["", "## Notes {#notes}", "", *_wrap(mission.notes)]
    out += ["", "[All missions](index.md) and [how a mission moves between states](index.md#lifecycle)."]
    return "\n".join(out) + "\n"


def index_page(missions: MissionList, covers: dict[int, Coverage]) -> str:
    """The overview: status counts, the checklist by group and the lifecycle."""
    out = [GENERATED, "", "# Missions", ""]
    out += _wrap(missions.about)
    out += ["", "## Status {#status}", "", "| Status | Missions | Meaning |", "| --- | --- | --- |"]
    for key, (_icon, _name, meaning) in STATUSES.items():
        count = sum(1 for m in missions.missions if m.status == key)
        out.append(f"| {label(key)} | {count} | {meaning} |")
    for group, title in GROUPS.items():
        members = [m for m in missions.missions if m.group == group]
        if not members:
            continue
        out += ["", f"## {title} {{#{group}}}", ""]
        out += [
            "| Mission | Level | Status | Checkpoints built | Approved | New bindings in Coney |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for m in members:
            cover = covers.get(m.level, NO_COVERAGE)
            out.append(
                f"| [{_cell(m.title)}]({m.name}.md) | `{m.name}` | {label(m.status)}"
                f" | {m.built()} of {len(m.checkpoints)} | {m.approved()} | {_bindings_cell(cover)} |"
            )
    out += ["", "## Lifecycle {#lifecycle}", ""]
    out += _wrap(missions.lifecycle)
    out.append("")
    out += _wrap(
        "Bindings numbers are those of [Story coverage](../references/bindings/story.md) and [Mission 1 coverage]"
        "(../references/bindings/mission1.md): the bindings a level is the first of the story to call, and how many of "
        "them Coney implements."
    )
    return "\n".join(out) + "\n"


def render(missions: MissionList, covers: dict[int, Coverage]) -> dict[str, str]:
    """Every page by file name inside docs/missions/."""
    pages = {"index.md": index_page(missions, covers)}
    for m in missions.missions:
        pages[f"{m.name}.md"] = mission_page(m, covers.get(m.level, NO_COVERAGE))
    return pages


def run_render(check_only: bool) -> int:
    """Write the pages, or with `check_only` report the stale ones and return 1."""
    root = find_repo_root(Path.cwd())
    masterlist = natives.load(root)
    pages = render(load(root), coverage(masterlist))
    folder = root / PAGES_DIR
    stale: list[str] = []
    for name, text in pages.items():
        path = folder / name
        current = path.read_bytes().decode("utf-8").replace("\r\n", "\n") if path.is_file() else None
        if current == text:
            continue
        stale.append(name)
        if not check_only:
            folder.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))
    # A page of a level that left the list is stale too.
    extra = sorted(p.name for p in folder.glob("*.md") if p.name not in pages) if folder.is_dir() else []
    for name in extra:
        stale.append(name)
        if not check_only:
            (folder / name).unlink()
    if check_only and stale:
        print("coney-tools: missions pages out of date (run `coney-tools missions render`):", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return 1
    print(f"{len(stale)} page(s) {'stale' if check_only else 'written'}; {len(pages) - 1} missions")
    return 0
