# SPDX-License-Identifier: GPL-3.0-or-later
"""The C++ signature table of the script bindings, generated from the masterlist for Coney's debug menus.

`coney-tools natives cpp` writes `src/debug/native_signatures.cpp` from `research/bindings/<category>.yaml`: every
binding's name, category and the shape of its arguments and results, which the debug menus use to build an argument
editor for any binding (docs/guides/debug-menu.md#natives). Only names, types and defaults go in: curated reference
data, never a description, game text or script source.
"""

from __future__ import annotations

import re
from pathlib import Path

from coney_tools.natives import CATEGORIES, Arg, Binding, Masterlist, Result

CPP_FILE = Path("src/debug/native_signatures.cpp")

# A number argument whose description says it takes a handle gets the handle editor (a number, shown as a handle).
_HANDLE = re.compile(r"\bhandle\b", re.IGNORECASE)


def _arg_type(arg: Arg) -> str:
    """The NativeArgType enumerator for one argument."""
    if arg.lua == "number":
        if _HANDLE.search(arg.desc):
            return "Handle"
        return "Integer" if arg.ctype in ("int", "unsigned") else "Number"
    if arg.lua == "table":
        return "StringTable" if arg.elem == "string" else "NumberTable"
    return {"boolean": "Boolean", "string": "String", "userdata": "Userdata"}[arg.lua]


def _default(arg: Arg) -> str:
    """An argument's default as C++ string literal text: `true`, `1`, `-1`; empty when it has none."""
    if arg.default is None:
        return ""
    if isinstance(arg.default, bool):
        return "true" if arg.default else "false"
    return str(arg.default).replace("\\", "\\\\").replace('"', '\\"')


def _result_type(result: Result) -> str:
    """The NativeResultType enumerator for one result."""
    return {"number": "Number", "boolean": "Boolean", "string": "String", "usertype": "Usertype"}[result.lua]


def _array_name(prefix: str, binding: Binding) -> str:
    """The name of a binding's argument or result array."""
    return f"k{prefix}_{binding.name}"


def render_cpp(masterlist: Masterlist) -> str:
    """The whole generated source: one argument and one result array per binding, then the table, by category in
    page order and by name within a category."""
    order = list(CATEGORIES)
    bindings = sorted(masterlist.bindings, key=lambda b: (order.index(b.category), b.name.lower(), b.name))
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by `uv run --project python coney-tools natives cpp` from research/bindings/*.yaml. Do not edit.",
        "// Names, categories and argument and result types only (curated reference data, LEGAL.md).",
        '#include "debug/native_signatures.h"',
        "",
        "#include <array>",
        "",
        "namespace coney::debug {",
        "",
        "namespace {",
        "",
        "// Short names keep the generated lines short.",
        "using A = NativeArgType;",
        "using R = NativeResultType;",
        "",
        "// clang-format off",
    ]
    for binding in bindings:
        args = binding.main.args
        if args:
            cells = ", ".join(f'{{"{a.name}", A::{_arg_type(a)}, "{_default(a)}", {a.count or 0}}}' for a in args)
            lines.append(f"constexpr std::array<NativeArg, {len(args)}> {_array_name('Args', binding)}{{{{{cells}}}}};")
        results = binding.main.results
        if results:
            cells = ", ".join(f"R::{_result_type(r)}" for r in results)
            lines.append(
                f"constexpr std::array<NativeResultType, {len(results)}> {_array_name('Results', binding)}{{{cells}}};"
            )
    lines.append(f"constexpr std::array<NativeSignature, {len(bindings)}> kSignatures{{{{")
    for binding in bindings:
        args_ref = _array_name("Args", binding) if binding.main.args else "{}"
        results_ref = _array_name("Results", binding) if binding.main.results else "{}"
        lines.append(
            f'    {{"{binding.name}", "{binding.category}", {args_ref}, {results_ref}, {len(binding.overloads)}}},'
        )
    lines += [
        "}};",
        "// clang-format on",
        "",
        "} // namespace",
        "",
        "std::span<const NativeSignature> nativeSignatures() { return kSignatures; }",
        "",
        "} // namespace coney::debug",
        "",
    ]
    return "\n".join(lines)
