# SPDX-License-Identifier: GPL-3.0-or-later
"""Rendering the script-binding masterlist into docs/references/bindings/: an index page, one page per category, the
first mission's coverage page and the story's."""

from __future__ import annotations

import textwrap
from typing import Any

from coney_tools.natives import CATEGORIES, EVIDENCE, STORY_LEVELS, Arg, Binding, Masterlist, Result, Variant

WIDTH = 120  # the docs' line length (.markdownlint.yaml, MD013)
GENERATED = "<!-- Generated by `coney-tools natives render` from research/bindings/. Do not edit by hand. -->"
TOTAL_CHUNKS = 467  # compiled Lua chunks in the NTSC-U WAD (scripting.md, survey)
VERIFIED = "Verified against: `SLUS_212.15` (NTSC-U, SHA1 `e9cb2cc49aa046b9e494313dce2f5038ed17b2f4`)."


def _wrap(text: str, indent: str = "") -> list[str]:
    """`text` as lines of at most WIDTH characters; blank-line-separated paragraphs stay separate."""
    lines: list[str] = []
    for i, paragraph in enumerate(p for p in text.split("\n\n") if p.strip()):
        if i:
            lines.append("")
        lines += textwrap.wrap(
            " ".join(paragraph.split()),
            WIDTH,
            initial_indent=indent,
            subsequent_indent=indent,
            break_long_words=False,
            break_on_hyphens=False,
        )
    return lines


def _bullet(text: str) -> list[str]:
    """`text` as a wrapped list item: `- ` on the first line, continuation lines indented two spaces."""
    lines = _wrap(text, "  ")
    return ["- " + lines[0][2:], *lines[1:]] if lines else []


def _cell(text: str) -> str:
    """`text` made safe for one table cell: one line, pipes escaped."""
    return " ".join(text.split()).replace("|", "\\|")


def _hex(addr: int) -> str:
    """An address as the docs write it: `0x` and eight hex digits, in code style."""
    return f"`0x{addr:08x}`"


def _default(value: Any) -> str:
    """A default value as Lua would write it."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f'"{value}"'
    return f"{value}"


def signature(name: str, variant: Variant) -> str:
    """The one-line signature, like `GetLevelId(index) -> number`."""
    head = f"{name}({', '.join(a.name for a in variant.args)})"
    if not variant.results:
        return head
    return f"{head} -> {', '.join(r.lua if r.lua != 'usertype' else (r.type or 'usertype') for r in variant.results)}"


def _read_as(arg: Arg) -> str:
    """How the wrapper reads an argument, in words."""
    if arg.lua == "number":
        kind = {
            "int": "number, truncated to an integer",
            "unsigned": "number, truncated to an unsigned integer",
            "float": "number (single precision)",
            "double": "number",
        }.get(arg.ctype or "double", "number")
    elif arg.lua == "boolean":
        kind = "boolean (nil or 0 is false)"
    elif arg.lua == "table":
        what = f"{arg.count} " if arg.count else ""
        kind = f"table of {what}{arg.elem}s ({'t[1]..t[' + str(arg.count) + ']' if arg.count else 't[1]...'})"
    elif arg.lua == "userdata":
        kind = "userdata (only read when given)"
    else:
        kind = arg.lua
    if arg.default is not None:
        kind += f"; default {_default(arg.default)}"
    if arg.lua == "table" and not arg.written_back:
        kind += "; not written back"
    return kind


def _result_kind(result: Result) -> str:
    """A result's Lua type in words."""
    if result.lua == "boolean":
        return "boolean (1 for true, nil for false)"
    if result.lua == "string":
        return "string (nil for none)"
    if result.lua == "usertype":
        return f"`{result.type}` object (nil for none)" if result.type else "tolua object (nil for none)"
    return "number"


def _variant_lines(name: str, variant: Variant) -> list[str]:
    """The signature, arguments table and results of one registration."""
    # A fenced block: long signatures stay on one line (MD013 skips code blocks) and read as code.
    out = ["```lua", signature(name, variant), "```", ""]
    if variant.args:
        out += ["| # | Argument | Read as | Meaning |", "| --- | --- | --- | --- |"]
        for i, arg in enumerate(variant.args, start=1):
            out.append(f"| {i} | `{arg.name}` | {_cell(_read_as(arg))} | {_cell(arg.desc) or '-'} |")
        out.append("")
    else:
        out += ["No arguments.", ""]
    if not variant.results:
        out += ["**Returns** nothing.", ""]
    elif len(variant.results) == 1:
        result = variant.results[0]
        text = f"**Returns** {_result_kind(result)}" + (f": {result.desc}" if result.desc else ".")
        out += [*_wrap(text), ""]
    else:
        out += ["**Returns:**", ""]
        for i, result in enumerate(variant.results, start=1):
            out.append(f"{i}. {_result_kind(result)}" + (f": {_cell(result.desc)}" if result.desc else ""))
        out.append("")
    return out


def _calls(variant: Variant) -> str:
    """The functions a wrapper calls, as `0x... Name` items."""
    items = [f"{_hex(c.addr)} `{c.name}`" if c.name else _hex(c.addr) for c in variant.calls]
    if variant.virtual_calls:
        items.append(f"{variant.virtual_calls} virtual call{'s' if variant.virtual_calls > 1 else ''}")
    return ", ".join(items) if items else "nothing (the wrapper does the work itself)"


def _yes(flag: bool) -> str:
    """A flag as yes/no."""
    return "yes" if flag else "no"


def _evidence(binding: Binding) -> str:
    """The evidence line: the level, and for confirmed (code) the address it was read at."""
    level = EVIDENCE[binding.evidence]
    where = [c.addr for c in binding.main.calls] or ([binding.main.wrapper] if binding.main.wrapper else [])
    if binding.evidence == "confirmed-code" and where:
        level += " at " + ", ".join(_hex(a) for a in where)
    detail = {"thorough": "traced", "brief": "brief", "mechanical": "signature only"}
    return f"{level}; detail: {detail[binding.depth]}"


def binding_section(binding: Binding) -> list[str]:
    """The section of one binding on its category page."""
    out = [f"## {binding.name} {{#{binding.anchor}}}", ""]
    out += _variant_lines(binding.name, binding.main)
    if binding.description:
        out += [*_wrap(binding.description), ""]
    else:
        out += ["*Not described yet: the signature above is read from the wrapper.*", ""]
    if binding.notes:
        out += [*_wrap(f"**Notes.** {binding.notes}"), ""]
    for i, over in enumerate(binding.overloads, start=1):
        label = "Overload" if len(binding.overloads) == 1 else f"Overload {i}"
        intro = (
            f"**{label}** (registered first; the wrapper above checks its argument types and calls this one when they"
            " do not match)" + (f": {over.note}" if over.note else ".")
        )
        out += [*_wrap(intro), ""]
        out += _variant_lines(binding.name, over)
        out += [*_wrap(f"Wrapper {_hex(over.wrapper) if over.wrapper else '-'}; calls {_calls(over)}."), ""]
    facts = [f"- **Evidence:** {_evidence(binding)}"]
    if binding.origin == "game":
        registrar = "`RegisterBindings`" if binding.registered_by == "RegisterBindings" else "the script system"
        wrapper = _hex(binding.main.wrapper) if binding.main.wrapper else "-"
        facts.append(f"- **Wrapper** {wrapper} (registered by {registrar}); **calls** {_calls(binding.main)}")
    else:
        facts.append("- **Origin:** added by Coney (not in the original game)")
    if binding.usage:
        u = binding.usage
        if u.calls:
            facts.append(
                f"- **Used by** {u.chunks} of {TOTAL_CHUNKS} script chunks"
                f" ({u.calls} reference{'s' if u.calls > 1 else ''}); boot to menu: {_yes(u.boot)};"
                f" mission 1: {_yes(u.mission1)}; result used: {_yes(u.result_used)}"
            )
            if u.levels:
                first = u.levels[0]
                facts.append(
                    f"- **Later in the story:** {len(u.levels)} of {len(STORY_LEVELS)} levels, first"
                    f" [`level{first}`](story.md#level{first}) ({_STORY_LABELS[first]})"
                )
        else:
            facts.append("- **Used by** no script on the disc")
    facts.append(f"- **Coney:** {binding.coney}")
    return out + [line for fact in facts for line in _bullet(fact[2:])] + [""]


def category_page(masterlist: Masterlist, category: str) -> str:
    """The page of one category."""
    title, scope = CATEGORIES[category]
    bindings = masterlist.by_category(category)
    out = [GENERATED, "", f"# Script bindings: {title}", "", VERIFIED, ""]
    out += _wrap(
        f"Bindings for {scope}: {len(bindings)} in all. Conventions, the other categories and how to read an entry are"
        " on the [masterlist](index.md)."
    )
    out += [
        "",
        "| Binding | Returns | Scripts | Boot | Mission 1 | Evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for b in bindings:
        returns = ", ".join(r.lua for r in b.main.results) or "-"
        u = b.usage
        scripts = str(u.chunks) if u else "-"
        boot = _yes(u.boot) if u else "-"
        mission = _yes(u.mission1) if u else "-"
        out.append(
            f"| [`{b.name}`](#{b.anchor}) | {returns} | {scripts} | {boot} | {mission} | {EVIDENCE[b.evidence]} |"
        )
    out.append("")
    for b in bindings:
        out += binding_section(b)
    return "\n".join(out).rstrip("\n") + "\n"


def _count(bindings: list[Binding], test: Any) -> int:
    """How many of `bindings` pass `test`."""
    return sum(1 for b in bindings if test(b))


def index_page(masterlist: Masterlist) -> str:
    """The masterlist's index page: what the bindings are, the conventions, the categories and the totals."""
    bindings = masterlist.bindings
    game = [b for b in bindings if b.origin == "game"]
    registrations = sum(1 + len(b.overloads) for b in game)
    overloaded = _count(game, lambda b: b.overloads)
    used = _count(game, lambda b: b.usage and b.usage.calls)
    boot = _count(game, lambda b: b.usage and b.usage.boot)
    mission = _count(game, lambda b: b.usage and b.usage.mission1)
    out = [GENERATED, "", "# Script bindings", "", VERIFIED, ""]
    out += _wrap(
        f"The game's scripts are Lua 4.0 chunks that drive the engine through **script bindings**: C++ functions the"
        f" game registers as Lua globals, playing the role FiveM calls *natives*. This is the masterlist of all"
        f" {len(game)} of them ({registrations} registrations, {overloaded} names registered twice as overloads),"
        f" one section per binding on the page of its category: its signature, what each argument means, what it"
        f" returns, what it does, how sure we are, the original functions behind it and how often the game's own"
        f" scripts call it. How the script system runs (the Lua state, the order of the scripts, callbacks by name)"
        f" is on [Scripts (Lua)](../../research/scripting.md)."
    )
    out.append("")
    out += _wrap(
        "The list doubles as the **API reference for script mods**: the planned mod system loads Lua mods from a"
        " mods folder and lets them call these same bindings ([Roadmap: script mods](../../roadmap.md#script-mods))."
        " The descriptions are written for that reader: what an argument means in game terms (a handle and where it"
        " comes from, an id, a unit), not only its Lua type."
    )
    out.append("")
    out += _wrap(
        "Everything here is generated by `coney-tools natives render` from the research database files"
        " `research/bindings/<category>.yaml` (schema:"
        " [Research workflow](../../guides/research-workflow.md#bindings)); edit the YAML, never these pages."
        " CI runs `coney-tools natives render --check`, which fails when the pages and the YAML disagree."
    )
    out += ["", "## Categories", "", "| Category | Bindings | Used by scripts | Boot to menu | Mission 1 | Traced |"]
    out.append("| --- | --- | --- | --- | --- | --- |")
    for category, (title, scope) in CATEGORIES.items():
        rows = [b for b in bindings if b.category == category]
        out.append(
            f"| [{title}]({category}.md): {scope} | {len(rows)}"
            f" | {_count(rows, lambda b: b.usage and b.usage.calls)}"
            f" | {_count(rows, lambda b: b.usage and b.usage.boot)}"
            f" | {_count(rows, lambda b: b.usage and b.usage.mission1)}"
            f" | {_count(rows, lambda b: b.depth == 'thorough')} |"
        )
    out.append(
        f"| **All** | **{len(bindings)}** | **{used}** | **{boot}** | **{mission}**"
        f" | **{_count(bindings, lambda b: b.depth == 'thorough')}** |"
    )
    out += ["", "## Conventions {#conventions}", ""]
    out += _wrap(
        "Each binding is a small wrapper made by tolua: it reads its arguments from the Lua stack with tolua's"
        " helpers, calls one function of the game and pushes the results. **No argument types are checked** (except"
        " in the overloads, below). An argument left off the end of the call reads as its default (0, false, no"
        " string, or the default the table gives) and an explicit nil as 0, false or no string; an argument of the"
        " wrong type reads as whatever Lua's conversion gives, usually 0. A wrong call therefore does something"
        " quietly wrong rather than raising an error, and script errors are silent anyway"
        " ([Scripts (Lua)](../../research/scripting.md#life-of-the-lua-state))."
    )
    out.append("")
    out += [
        "| Read as | What the script passes |",
        "| --- | --- |",
        "| number | any number |",
        "| number, truncated to an integer | an integer; a fraction is cut off toward zero |",
        "| number, truncated to an unsigned integer | a **handle** (of a human, object, camera, gang, ...) as an"
        " earlier binding returned it, or a non-negative id; `NilHandle` is the global for no handle |",
        "| number (single precision) | a number the engine keeps as a 32-bit float: positions in metres, angles,"
        " times in seconds unless the meaning says otherwise |",
        "| boolean (nil or 0 is false) | `true` (1) or `false` (nil); any number other than 0 is true |",
        "| string | a name, passed to the engine as text; nil reads as no string |",
        "| table of 3 numbers (t[1]..t[3]) | a position or vector `{x, y, z}`, read by index (not `.x`) |",
        "| table of 4 numbers (t[1]..t[4]) | a rotation quaternion or colour `{a, b, c, d}`, read by index |",
        "| (any table) | after the call the wrapper copies the values back into the table it was given, so a binding"
        " that changes them (`HuCreate` snaps the position to the ground) returns them this way; every table"
        " argument of the game's bindings is written back |",
        "| userdata | a C pointer passed through from another binding; only read when the caller passed it |",
        "",
    ]
    out += _wrap(
        "**Results.** A binding pushes at most one value. Lua 4.0 has no booleans, so a boolean result is the number"
        " **1 for true and nil for false** (`global.lua` sets `true = 1` and `false = nil` to match); test it with"
        " `if x then` (in Lua every value but nil is true, 0 included). A string result is nil when there is none, and"
        " an object result (`M_Vector4`, a tolua class with fields `x y z w`) is nil for none. A binding listed as"
        " returning nothing pushes no value, so its call evaluates to nil."
    )
    out.append("")
    out += _wrap(
        "**Overloads.** Ten names are registered twice. Lua keeps the second registration; its wrapper checks the"
        " types of the arguments it was given and, when they do not match, calls the first registration instead. So"
        " both forms work, chosen by the argument types; each such entry shows both."
    )
    out.append("")
    out += _wrap(
        "**Callbacks.** Bindings that take a function name (`ScheduleFunc`, `SetMsgHandler`, `PadSetHandler`, ...)"
        " keep the name, not the function, and look it up when they fire; a dotted name such as `Menu.onStart`"
        " finds a field of a global table ([Scripts (Lua)](../../research/scripting.md#calling-lua-from-c))."
    )
    out += ["", "## How to read an entry {#how-to-read}", ""]
    out += _wrap(
        "Each section starts with the **signature**, like `GetLevelId(index) -> number`: the argument names are ours,"
        " in the order the wrapper reads them, and the arrow gives the Lua type of what it returns (nothing when"
        " there is no arrow). The table gives each argument's position, how the wrapper reads it (the rows of the"
        " table above) and its meaning in game terms. Then come the description and the facts:"
    )
    out.append("")
    for item in (
        "**Evidence:** the [evidence level](../../guides/research-workflow.md#evidence-levels) of the description"
        " and meanings, and the detail: *traced* means the analyst followed the function behind the wrapper far"
        " enough to describe every argument; *brief* means a shorter description from a quick read of that function,"
        " the binding's name and how the game's scripts call it (the evidence level says which of these it rests"
        " on). The signature itself (argument count, order, Lua types, results) is always confirmed (code) at the"
        " wrapper.",
        "**Wrapper / calls:** the address of the tolua wrapper and of the function of the game it calls (with our"
        " name for it when it has one), in `SLUS_212.15`.",
        f"**Used by:** how many of the {TOTAL_CHUNKS} compiled Lua chunks on the disc use the binding, how many"
        " references to it there are in all, whether the scripts of the boot-to-menu path or of the first mission use"
        " it, and whether a call was seen to use its result (below).",
        "**Coney:** whether Coney implements the binding yet (below).",
    ):
        out += _bullet(item)
    out += ["", "## Usage counts {#usage}", ""]
    out += _wrap(
        f"The counts come from a survey of the NTSC-U disc's {TOTAL_CHUNKS} compiled Lua chunks, reporting names and"
        " counts only. Every `GETGLOBAL` of a binding's name counts as a reference: the scripts fetch a binding by"
        " its global name to call it (often inside a loop, which is why references, not traced calls, are counted)."
        " *Result used* is a lower bound: it says a traced call was seen to keep the binding's result."
        f" {used} of the {len(game)} bindings are used somewhere and {len(game) - used} never. The **boot-to-menu"
        " path** is `enum_preload.lua`, the three `config_preload*.lua`, `config_strings_en.lua`, `global.lua` and"
        f" `level100.lua` ({boot} bindings); **mission 1** is `level99.lua`, `level99_combat.lua`,"
        " `level99_lesson1.lua` and `level99_lesson2.lua`, the `global.lua` helpers they reach (by name, as a"
        " `Table.field` or as a callback string, transitively) and the two helpers the engine calls when a mission"
        f" ends, `UnlockAndLoad` and `runNextMission` ({mission} bindings, listed with their status on"
        " [Mission 1 coverage](mission1.md); `coney-tools natives mission1` sets the marker from the disc). Each later"
        " level of the story is read the same way, and its bindings are listed on [Story coverage](story.md)"
        " (`coney-tools natives missions`). A binding"
        " no script uses still works if a mod calls it, but nothing in the game has exercised it, so its description"
        " is less certain."
    )
    out += ["", "## Coney status {#coney-status}", ""]
    out += _wrap(
        "Every entry has a **Coney** field: *not implemented*, *partial* or *implemented*, the default being *not"
        " implemented*. It is the `coney` key of the entry in `research/bindings/`, which"
        " `coney-tools natives coney` sets from Coney's own binding table (`src/scripting/script_bindings.cpp`), so it"
        " is never kept up to date by hand: a binding Coney implements is *implemented*, one it hands to a stand-in"
        " for a subsystem it does not have yet is *partial*, and a stub, or a binding missing from the table, is *not"
        " implemented*. CI fails when the field and the table disagree."
    )
    out.append("")
    out += _wrap(
        "Bindings that Coney adds for mods (with no counterpart in the game) will go in the same file with"
        " `origin: coney`; they have no wrapper address or usage counts. There are none yet."
    )
    out += ["", "## Evidence and detail {#evidence}", "", "| | Bindings |", "| --- | --- |"]
    for key, label in EVIDENCE.items():
        out.append(f"| {label} | {_count(bindings, lambda b, k=key: b.evidence == k)} |")
    for depth, label in (("thorough", "traced"), ("brief", "brief")):
        out.append(f"| detail: {label} | {_count(bindings, lambda b, d=depth: b.depth == d)} |")
    mechanical = _count(bindings, lambda b: b.depth == "mechanical")
    if mechanical:
        out.append(f"| detail: signature only | {mechanical} |")
    out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def mission_page(masterlist: Masterlist) -> str:
    """The first mission's coverage page: every binding its scripts can call, with how far each is researched and
    whether Coney implements it."""
    rows = sorted(
        (b for b in masterlist.bindings if b.usage and b.usage.mission1),
        key=lambda b: (list(CATEGORIES).index(b.category), b.name.lower()),
    )
    traced = _count(rows, lambda b: b.depth == "thorough")
    done = _count(rows, lambda b: b.coney == "implemented")
    partial = _count(rows, lambda b: b.coney == "partial")
    out = [GENERATED, "", "# Script bindings: mission 1 coverage", "", VERIFIED, ""]
    out += _wrap(
        f'The {len(rows)} bindings the first mission can call, for the milestone "the first mission playable from the'
        ' title screen to its end": the scripts `level99.lua`, `level99_combat.lua`, `level99_lesson1.lua` and'
        " `level99_lesson2.lua`, the `global.lua` helpers they reach, and the helpers the engine calls when the"
        " mission ends (`UnlockAndLoad`, `runNextMission`). The set is an upper bound (a branch the mission never takes"
        " still counts); how it is found is under [Usage counts](index.md#usage), and the mission's flow is on"
        " [Scripts (Lua)](../../research/scripting.md#level99)."
    )
    out.append("")
    out += _wrap(
        f"**Researched:** {traced} of {len(rows)} are traced (the function behind the wrapper followed far enough to"
        f" describe every argument). **Coney:** {done} implemented, {partial} partial,"
        f" {len(rows) - done - partial} not yet ([Coney status](index.md#coney-status)). A traced binding can still"
        " leave part of its effect open; its notes say which."
    )
    out += ["", "| Binding | Category | Detail | Evidence | Coney |", "| --- | --- | --- | --- | --- |"]
    for b in rows:
        detail = "traced" if b.depth == "thorough" else b.depth
        out.append(
            f"| [`{b.name}`]({b.category}.md#{b.anchor}) | {CATEGORIES[b.category][0]} | {detail}"
            f" | {EVIDENCE[b.evidence]} | {b.coney} |"
        )
    return "\n".join(out) + "\n"


_STORY_LABELS = dict(STORY_LEVELS)


def _row(b: Binding) -> str:
    """One binding's row in a coverage table: link, category, detail, evidence and Coney status."""
    detail = "traced" if b.depth == "thorough" else b.depth
    return (
        f"| [`{b.name}`]({b.category}.md#{b.anchor}) | {CATEGORIES[b.category][0]} | {detail}"
        f" | {EVIDENCE[b.evidence]} | {b.coney} |"
    )


def story_page(masterlist: Masterlist) -> str:
    """The story's coverage page: for each level after the first, in story order, how many bindings its scripts can
    call and the ones no earlier level calls, with how far each is researched and whether Coney implements it."""
    game = [b for b in masterlist.bindings if b.usage]
    seen = {b.name for b in game if b.usage and b.usage.mission1}
    out = [GENERATED, "", "# Script bindings: story coverage", "", VERIFIED, ""]
    out += _wrap(
        "The bindings each level of the story after the first can call, in the order a player meets the levels:"
        " missions 2-18 with the hub (`level95`) between them, then the hub's five flashback missions and the Armies"
        " of the Night bonus game ([Scripts (Lua)](../../research/scripting.md#run-next-mission) has the order and"
        " what loads each level). A level's scripts are `levelNN.lua` and its `levelNN_*.lua` chapters (without the"
        " language files and the scene tests), read with the reach rule of [Mission 1 coverage](mission1.md): the"
        " `global.lua` helpers they reach and the engine's two end-of-mission callbacks count too, so each set is an"
        " upper bound. **New** are the bindings no earlier level calls, the first mission's included: implementing"
        " the levels in order, these are the ones each level adds. `coney-tools natives missions` sets each entry's"
        " `usage.levels` from the disc."
    )
    out += [
        "",
        "| Level | Story | Bindings | New | New, traced | New, in Coney |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    sections: list[str] = []
    for level, label in STORY_LEVELS:
        used = [b for b in game if b.usage and level in b.usage.levels]
        new = sorted(
            (b for b in used if b.name not in seen),
            key=lambda b: (list(CATEGORIES).index(b.category), b.name.lower()),
        )
        seen |= {b.name for b in used}
        traced = _count(new, lambda b: b.depth == "thorough")
        done = _count(new, lambda b: b.coney == "implemented")
        out.append(f"| [`level{level}`](#level{level}) | {label} | {len(used)} | {len(new)} | {traced} | {done} |")
        sections += ["", f"## level{level}: {label} {{#level{level}}}", ""]
        sections += _wrap(
            f"{len(used)} bindings, {len(new)} new: {traced} traced, {done} implemented in Coney"
            f" ({_count(used, lambda b: b.coney == 'implemented')} of all {len(used)})."
        )
        if new:
            sections += ["", "| Binding | Category | Detail | Evidence | Coney |", "| --- | --- | --- | --- | --- |"]
            sections += [_row(b) for b in new]
    return "\n".join(out + sections) + "\n"


def render(masterlist: Masterlist) -> dict[str, str]:
    """Every page, by file name inside docs/references/bindings/."""
    pages = {"index.md": index_page(masterlist)}
    # Every category gets a page, even an empty one, so the navigation in mkdocs.yml never points at a missing file.
    for category in CATEGORIES:
        pages[f"{category}.md"] = category_page(masterlist, category)
    pages["mission1.md"] = mission_page(masterlist)
    pages["story.md"] = story_page(masterlist)
    return pages
