# SPDX-License-Identifier: GPL-3.0-or-later
"""Markdown for the progress tracker: the README's Progress section and the docs page's generated part.

Bars are Unicode block characters in Markdown tables, so they render the same on GitHub and on the MkDocs site
without any CSS. The generated text sits between MARKER_START and MARKER_END; everything outside the markers is
written by hand.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from urllib.parse import quote

from coney_tools.progress import UNATTRIBUTED, Progress, ProgressError

MARKER_START = "<!-- progress:start -->"
MARKER_END = "<!-- progress:end -->"
GENERATED_NOTE = (
    "<!-- Generated by `coney-tools progress update` from docs/progress/*.toml, the @orig tags in src/\n"
    "     and the roadmap's status table. Edit those, not this. -->"
)
BAR_WIDTH = 20
_EIGHTHS = " ▏▎▍▌▋▊▉"
_FULL = "█"
_EMPTY = "░"


def bar(part: int, whole: int, width: int = BAR_WIDTH) -> str:
    """A bar of `width` cells, filled in eighths of a cell, as a code span so every cell has the same width."""
    fraction = min(max(part / whole, 0.0), 1.0) if whole > 0 else 0.0
    eighths = round(fraction * width * 8)
    if part > 0 and whole > 0 and eighths == 0:
        eighths = 1  # any progress at all shows
    full, rest = divmod(eighths, 8)
    cells = _FULL * full + (_EIGHTHS[rest] if rest else "")
    return f"`{cells}{_EMPTY * (width - len(cells))}`"


def percent(part: int, whole: int) -> str:
    """`part` of `whole` as a percentage with one decimal; a share too small to show is `<0.1%`."""
    if whole <= 0:
        return "n/a"
    value = 100.0 * part / whole
    if 0 < value < 0.05:
        return "<0.1%"
    return f"{value:.1f}%"


def badge_url(label: str, part: int, whole: int) -> str:
    """A shields.io static badge for a percentage, coloured from grey (nothing yet) to green."""
    value = 100.0 * part / whole if whole > 0 else 0.0
    color = "lightgrey"
    for threshold, name in ((0.0, "red"), (10.0, "orange"), (30.0, "yellow"), (60.0, "yellowgreen"), (90.0, "green")):
        if part > 0 and value >= threshold:
            color = name
    # In a static badge path, `-` separates the fields, so a literal one is doubled; `%` must be escaped.
    text = quote(percent(part, whole).replace("-", "--"), safe="")
    return f"https://img.shields.io/badge/{quote(label.replace('-', '--'), safe='')}-{text}-{color}"


def _summary_rows(progress: Progress, roadmap_link: str) -> list[str]:
    """The summary table shared by the README and the docs page; `roadmap_link` is relative to each."""
    totals = progress.totals
    game = totals.game_bytes
    done = progress.reimplemented_bytes
    milestones = progress.milestones
    finished = sum(1 for m in milestones if m.status == "done")
    count = len(progress.functions)
    return [
        "| | Progress | Share |",
        "| --- | --- | --- |",
        f"| **Reimplemented** | {bar(done, game)} | {percent(done, game)} of the game's own code "
        f"({done:,} of {game:,} bytes, {count:,} function{'' if count == 1 else 's'}) |",
        f"| **Researched** | {bar(totals.researched_bytes, game)} | {percent(totals.researched_bytes, game)} "
        f"placed in a source file or directory ({totals.researched_bytes:,} bytes) |",
        f"| **[Milestones]({roadmap_link})** | {bar(finished, len(milestones))} "
        f"| {finished} of {len(milestones)} done |",
    ]


def _badges(progress: Progress) -> str:
    """The two shields.io badges, reimplemented and researched."""
    game = progress.totals.game_bytes
    reimplemented = badge_url("reimplemented", progress.reimplemented_bytes, game)
    researched = badge_url("researched", progress.totals.researched_bytes, game)
    return (
        f"![Reimplemented: {percent(progress.reimplemented_bytes, game)}]({reimplemented}) "
        f"![Researched: {percent(progress.totals.researched_bytes, game)}]({researched})"
    )


def _current(progress: Progress, roadmap_link: str) -> str:
    """The "Working on: ..." line naming the milestones in progress; empty when there are none."""
    current = [m for m in progress.milestones if m.status == "in progress"]
    if not current:
        return ""
    names = ", ".join(f"[{m.name}]({roadmap_link}#{m.anchor})" for m in current)
    # Wrapped at 120 columns, as the docs' line-length rule asks; a link may break between words.
    return textwrap.fill(f"Working on: {names}.", width=120, break_long_words=False, break_on_hyphens=False)


def render_readme(progress: Progress) -> str:
    """The README's generated Progress block (without the markers)."""
    lines = [_badges(progress), "", *_summary_rows(progress, "docs/roadmap.md"), ""]
    current = _current(progress, "docs/roadmap.md")
    if current:
        lines.append(current)
    lines.append(
        "Per subsystem, the research coverage, the middleware and how it is all measured: "
        "[Progress](docs/progress/index.md)."
    )
    return "\n".join(lines)


def _subsystem_table(progress: Progress) -> list[str]:
    """One row per subsystem, then unattributed code; a subsystem with no placed bytes shows n/a."""
    lines = [
        "| Subsystem | Reimplemented | Share | Functions | Code (bytes) |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name, total, done, count in progress.subsystem_rows():
        label = "Unattributed" if name == UNATTRIBUTED else f"`{name}`"
        if total == 0:
            lines.append(f"| {label} | {bar(0, 0)} | n/a | {count} | not placed yet |")
        else:
            lines.append(f"| {label} | {bar(done, total)} | {percent(done, total)} | {count} | {total:,} |")
    return lines


def _coverage_table(progress: Progress) -> list[str]:
    """The source map's coverage categories as shares of `.text`."""
    text = progress.totals.text.size
    lines = ["| Category | Share of `.text` | | Bytes |", "| --- | --- | --- | --- |"]
    for c in progress.totals.coverage:
        lines.append(f"| {c.label} | {bar(c.bytes, text)} | {percent(c.bytes, text)} | {c.bytes:,} |")
    return lines


def _middleware_table(progress: Progress) -> list[str]:
    """The middleware Coney replaces, with its share of `.text`."""
    text = progress.totals.text.size
    lines = ["| Library | Share of `.text` | Bytes | Replaced by |", "| --- | --- | --- | --- |"]
    for m in progress.totals.middleware:
        lines.append(f"| {m.name} | {percent(m.bytes, text)} | {m.bytes:,} | {m.replaced_by} |")
    return lines


def _function_table(progress: Progress) -> list[str]:
    """Every reimplemented function in address order, or "None yet."."""
    if not progress.functions:
        return ["None yet."]
    lines = ["| Address | Original name | Subsystem | Bytes |", "| --- | --- | --- | --- |"]
    for f in sorted(progress.functions, key=lambda f: f.address):
        size = f"{f.size:,}" if f.size is not None else "not filled in"
        lines.append(f"| `{f.address:#010x}` | `{f.name}` | `{f.subsystem}` | {size} |")
    return lines


def render_page(progress: Progress) -> str:
    """The docs page's generated block (without the markers)."""
    lines = ["## Overall", "", _badges(progress), "", *_summary_rows(progress, "../roadmap.md"), ""]
    missing = sum(1 for f in progress.functions if f.size is None)
    if missing:
        lines += [f"{missing} reimplemented function(s) have no size yet and add no bytes.", ""]
    lines += ["## Milestones", "", "| Milestone | Status |", "| --- | --- |"]
    lines += [f"| [{m.name}](../roadmap.md#{m.anchor}) | {m.status} |" for m in progress.milestones]
    lines += ["", "## By subsystem", "", *_subsystem_table(progress), ""]
    lines += ["## Research coverage", "", *_coverage_table(progress), ""]
    lines += ["## Middleware: replaced, not reimplemented", "", *_middleware_table(progress), ""]
    lines += ["## Reimplemented functions", "", *_function_table(progress)]
    return "\n".join(lines)


def replace_block(text: str, block: str, path: Path) -> str:
    """`text` with everything between the progress markers replaced by the generated note and `block`."""
    start = text.find(MARKER_START)
    end = text.find(MARKER_END)
    if start < 0 or end < start:
        raise ProgressError(f"{path}: no {MARKER_START} ... {MARKER_END} block to fill")
    return f"{text[: start + len(MARKER_START)]}\n{GENERATED_NOTE}\n{block}\n{text[end:]}"
