# SPDX-License-Identifier: GPL-3.0-or-later
"""The "Understood" measure of the progress tracker: how much of the game's code is researched, not just placed.

A game function counts as understood when both hold:

* it has a meaningful name in the shared Ghidra project (not Ghidra's default `FUN_<address>`), and
* its address is cited in docs/research/** (the source map excepted: placing a function is not understanding it)
  in a table row or paragraph that states an evidence level (confirmed, inferred, speculative) or says
  `not needed: <reason>`, or it is the wrapper of a script binding in research/bindings/*.yaml with an `evidence`.

The names and sizes come from a committed listing, docs/progress/ghidra-functions.tsv, exported from Ghidra by
`coney-tools progress ghidra`: addresses, sizes and our own names only, which LEGAL.md allows as reference data.
The citations are read from the docs on every `progress update`, so a research page that cites a function moves
the bar in the same commit. docs/guides/research-workflow.md#understood says how to refresh the listing.
"""

from __future__ import annotations

import json
import re
import urllib.error
import urllib.request
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from coney_tools.progress import UNATTRIBUTED, ProgressError, Totals

LISTING_FILE = Path("docs/progress/ghidra-functions.tsv")
RESEARCH_DIR = Path("docs/research")
BINDINGS_DIR = Path("research/bindings")
#: Pages whose citations do not count: the source map only places functions in files and directories.
NOT_UNDERSTANDING = frozenset({"source-map.md"})
DEFAULT_GHIDRA_URL = "http://127.0.0.1:8090"

LISTING_HEADER = (
    "# Every function of SLUS_212.15 that the shared Ghidra project knows: address, size in bytes, our name (empty\n"
    "# while Ghidra's default FUN_<address>) and whether it has a plate comment (1/0). Reference data only: no code.\n"
    "# Generated by `coney-tools progress ghidra` (docs/guides/research-workflow.md#understood); do not edit.\n"
)
_DEFAULT_NAME = re.compile(r"^(?:thunk_)?(?:FUN|SUB|LAB)_[0-9a-fA-F]{8}$")
_EVIDENCE = re.compile(r"\b(?:confirmed|inferred|speculative)\b|not needed", re.IGNORECASE)
_ADDRESS = re.compile(r"\b0x([0-9a-fA-F]{8})\b")
_WRAPPER = re.compile(r"^\s*wrapper:\s*0x([0-9a-fA-F]{8})\b", re.MULTILINE)
_BINDING_EVIDENCE = re.compile(r"^\s*evidence:\s*\S", re.MULTILINE)
_BINDING_NAME = re.compile(r"^\s*name:\s*(\S+)", re.MULTILINE)
#: The first code-span identifier after an address on its line: the name the page gives the function, a guess.
_PAGE_NAME = re.compile(r"`(~?[A-Za-z_][A-Za-z0-9_]*(?:::~?[A-Za-z_][A-Za-z0-9_]*)*)`")


@dataclass(frozen=True)
class ListedFunction:
    """One function of the Ghidra listing."""

    address: int
    size: int
    name: str  # empty while Ghidra's name is the default
    plate: bool

    @property
    def named(self) -> bool:
        """True when the function has a meaningful name."""
        return bool(self.name) and not _DEFAULT_NAME.match(self.name)


@dataclass
class Citation:
    """Where the research cites one address."""

    evidence: bool = False
    pages: set[str] = field(default_factory=set)
    page_name: str = ""


@dataclass(frozen=True)
class FunctionStatus:
    """A game function and what it still lacks to count as understood."""

    function: ListedFunction
    subsystem: str
    citation: Citation | None

    @property
    def cited(self) -> bool:
        """Cited with an evidence level (or a deliberate "not needed")."""
        return self.citation is not None and self.citation.evidence

    @property
    def understood(self) -> bool:
        """Named and cited with evidence."""
        return self.function.named and self.cited

    def missing(self) -> list[str]:
        """What is still needed: `name`, `cite` (no page cites it) or `evidence` (cited, no evidence level)."""
        needs = [] if self.function.named else ["name"]
        if self.citation is None:
            needs.append("cite")
        elif not self.citation.evidence:
            needs.append("evidence")
        return needs


@dataclass(frozen=True)
class SubsystemUnderstanding:
    """Totals for one subsystem (or unattributed code)."""

    name: str
    functions: int
    understood_functions: int
    bytes: int
    understood_bytes: int
    named: int
    cited: int


@dataclass
class Understanding:
    """The measure over every game function of the listing."""

    statuses: list[FunctionStatus]

    @property
    def functions(self) -> int:
        """Game functions in the listing."""
        return len(self.statuses)

    @property
    def bytes(self) -> int:
        """Bytes of the game functions in the listing."""
        return sum(s.function.size for s in self.statuses)

    @property
    def understood_functions(self) -> int:
        """Game functions that count as understood."""
        return sum(1 for s in self.statuses if s.understood)

    @property
    def understood_bytes(self) -> int:
        """Bytes of the game functions that count as understood."""
        return sum(s.function.size for s in self.statuses if s.understood)

    def by_subsystem(self, order: list[str]) -> list[SubsystemUnderstanding]:
        """One row per subsystem in `order` that has functions, then any others (unattributed last)."""
        groups: dict[str, list[FunctionStatus]] = {}
        for status in self.statuses:
            groups.setdefault(status.subsystem, []).append(status)
        names = [n for n in order if n in groups] + sorted(n for n in groups if n not in order and n != UNATTRIBUTED)
        if UNATTRIBUTED in groups:
            names.append(UNATTRIBUTED)
        rows = []
        for name in names:
            group = groups[name]
            done = [s for s in group if s.understood]
            rows.append(
                SubsystemUnderstanding(
                    name,
                    len(group),
                    len(done),
                    sum(s.function.size for s in group),
                    sum(s.function.size for s in done),
                    sum(1 for s in group if s.function.named),
                    sum(1 for s in group if s.cited),
                )
            )
        return rows

    def backlog(self, subsystem: str) -> list[FunctionStatus]:
        """The subsystem's functions not yet understood, largest first."""
        todo = [s for s in self.statuses if s.subsystem == subsystem and not s.understood]
        return sorted(todo, key=lambda s: (-s.function.size, s.function.address))


# --- the listing ------------------------------------------------------------------------------------------------------


def parse_listing(text: str, path: Path = LISTING_FILE) -> list[ListedFunction]:
    """Parse the listing's lines `0x<address>\\t<size>\\t<name>\\t<plate>`; `#` lines are comments."""
    functions = []
    for number, line in enumerate(text.splitlines(), start=1):
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 4 or not re.fullmatch(r"0x[0-9a-f]{8}", fields[0]) or not fields[1].isdigit():
            raise ProgressError(f"{path}:{number}: expected `0x<address>\\t<size>\\t<name>\\t<0|1>`, got {line!r}")
        if fields[3] not in ("0", "1"):
            raise ProgressError(f"{path}:{number}: the plate column must be 0 or 1")
        functions.append(ListedFunction(int(fields[0], 16), int(fields[1]), fields[2], fields[3] == "1"))
    addresses = [f.address for f in functions]
    if addresses != sorted(set(addresses)):
        raise ProgressError(f"{path}: addresses must be unique and in ascending order")
    return functions


def format_listing(functions: list[ListedFunction]) -> str:
    """The listing's text: the header, then one line per function in address order."""
    lines = [LISTING_HEADER.rstrip("\n")]
    for f in sorted(functions, key=lambda f: f.address):
        name = "" if f.name == f"FUN_{f.address:08x}" else f.name
        lines.append(f"0x{f.address:08x}\t{f.size}\t{name}\t{int(f.plate)}")
    return "\n".join(lines) + "\n"


def load_listing(path: Path) -> list[ListedFunction] | None:
    """The listing at `path`, or None when there is none yet."""
    try:
        text = path.read_bytes().decode("utf-8")
    except FileNotFoundError:
        return None
    except (OSError, UnicodeDecodeError) as error:
        raise ProgressError(f"{path}: cannot be read ({error})") from error
    return parse_listing(text, path)


#: Fetches a ghidra-mcp HTTP path (with its query) and returns the decoded JSON.
Fetch = Callable[[str], Any]


def http_fetch(base_url: str) -> Fetch:
    """A Fetch against a running ghidra-mcp server (read-only endpoints only)."""

    # One GET per call; a failure names the server so the user knows to start it.
    def fetch(path: str) -> Any:
        try:
            with urllib.request.urlopen(base_url + path, timeout=120) as response:
                return json.loads(response.read().decode("utf-8"))
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as error:
            raise ProgressError(f"ghidra-mcp at {base_url}: {error} (is the server running?)") from error

    return fetch


def export_listing(fetch: Fetch, batch: int = 200) -> list[ListedFunction]:
    """Every function of the open program, with its size and whether it has a plate comment, read through `fetch`.

    Uses only reading endpoints, so it is safe on the shared server while other analysts work in it.
    """
    listed = fetch("/list_functions_enhanced?limit=100000&offset=0")["functions"]
    entries = [item for item in listed if not item.get("isExternal")]
    sizes: dict[int, int] = {}
    for item in entries:
        info = fetch(f"/get_function_by_address?address=0x{item['address']}")
        sizes[int(item["address"], 16)] = int(info["body_end"], 16) - int(info["body_start"], 16) + 1
    plates: set[int] = set()
    for i in range(0, len(entries), batch):
        addresses = ",".join(f"0x{item['address']}" for item in entries[i : i + batch])
        for result in fetch(f"/batch_get_comments?addresses={addresses}")["results"]:
            if (result.get("plate") or "").strip():
                plates.add(int(result["address"], 16))
    functions = []
    for item in entries:
        address = int(item["address"], 16)
        functions.append(ListedFunction(address, sizes[address], item["name"], address in plates))
    return sorted(functions, key=lambda f: f.address)


# --- the citations ----------------------------------------------------------------------------------------------------


def _blocks(text: str) -> list[list[str]]:
    """A Markdown page cut into the units a claim lives in: each table row alone, else each paragraph."""
    blocks: list[list[str]] = []
    current: list[str] = []
    for line in text.splitlines():
        if line.lstrip().startswith("|") or not line.strip():
            if current:
                blocks.append(current)
                current = []
            if line.strip():
                blocks.append([line])
        else:
            current.append(line)
    if current:
        blocks.append(current)
    return blocks


def _cite(citations: dict[int, Citation], address: int, page: str, evidence: bool, name: str) -> None:
    """Record one citation of `address`."""
    citation = citations.setdefault(address, Citation())
    citation.evidence = citation.evidence or evidence
    citation.pages.add(page)
    if name and not citation.page_name:
        citation.page_name = name


def scan_citations(root: Path) -> dict[int, Citation]:
    """Every address the research pages and binding files cite, with whether a citation states its evidence."""
    citations: dict[int, Citation] = {}
    research = root / RESEARCH_DIR
    pages = sorted(p for p in research.rglob("*.md") if p.name not in NOT_UNDERSTANDING) if research.is_dir() else []
    for path in pages:
        page = path.relative_to(root / "docs").as_posix()
        for block in _blocks(path.read_text(encoding="utf-8", errors="replace")):
            evidence = bool(_EVIDENCE.search("\n".join(block)))
            for line in block:
                for match in _ADDRESS.finditer(line):
                    found = _PAGE_NAME.search(line[match.end() : match.end() + 120])
                    name = found.group(1) if found and not found.group(1).startswith("FUN_") else ""
                    _cite(citations, int(match.group(1), 16), page, evidence, name)
    bindings = root / BINDINGS_DIR
    for path in sorted(bindings.glob("*.yaml")) if bindings.is_dir() else []:
        page = path.relative_to(root).as_posix()
        for entry in re.split(r"\n- ", path.read_text(encoding="utf-8", errors="replace")):
            wrapper = _WRAPPER.search(entry)
            if wrapper:
                name = _BINDING_NAME.search(entry.lstrip().removeprefix("- "))
                evidence = bool(_BINDING_EVIDENCE.search(entry))
                _cite(citations, int(wrapper.group(1), 16), page, evidence, f"lua_{name.group(1)}" if name else "")
    return citations


def measure(totals: Totals, functions: list[ListedFunction], citations: dict[int, Citation]) -> Understanding:
    """The measure over the listing's game functions (middleware and anything outside `.text` left out)."""
    statuses = []
    for f in functions:
        subsystem = totals.subsystem_of(f.address)
        if subsystem is not None:
            statuses.append(FunctionStatus(f, subsystem, citations.get(f.address)))
    return Understanding(statuses)


def load(root: Path, totals: Totals) -> Understanding | None:
    """The measure for the checkout at `root`, or None when it has no listing yet."""
    functions = load_listing(root / LISTING_FILE)
    if functions is None:
        return None
    return measure(totals, functions, scan_citations(root))


# --- the backlog ------------------------------------------------------------------------------------------------------


def backlog_file_name(subsystem: str) -> str:
    """A file name for a subsystem's backlog: `Device/ps2` becomes `Device-ps2.md`."""
    if subsystem == UNATTRIBUTED:
        return "Unattributed.md"
    return re.sub(r"[^A-Za-z0-9_-]+", "-", subsystem.split(" (")[0]).strip("-") + ".md"


def render_backlog(understanding: Understanding, row: SubsystemUnderstanding) -> str:
    """One subsystem's backlog as Markdown: every function not yet understood, largest first."""
    todo = understanding.backlog(row.name)
    rename_only = sum(1 for s in todo if s.missing() == ["name"])
    share = f"{100.0 * row.understood_bytes / row.bytes:.1f}%" if row.bytes else "n/a"
    lines = [
        f"# Research backlog: {row.name}",
        "",
        f"{row.understood_functions} of {row.functions} functions understood ({row.understood_bytes:,} of "
        f"{row.bytes:,} bytes, {share}). {len(todo)} to do, largest first; {rename_only} only need a Ghidra name "
        "(and a plate comment), because a page already documents them.",
        "",
        "Missing: `name` = still Ghidra's default name; `cite` = no research page cites it; `evidence` = cited, but "
        "not in a row or paragraph that states an evidence level. The page name is a guess from the citing line.",
        "",
        "| Address | Size | Ghidra name | Missing | Plate | Name on the page | Cited on |",
        "| --- | ---: | --- | --- | --- | --- | --- |",
    ]
    for s in todo:
        f = s.function
        name = f.name or f"FUN_{f.address:08x}"
        citation = s.citation or Citation()
        page_name = f"`{citation.page_name}`" if citation.page_name else ""
        lines.append(
            f"| `0x{f.address:08x}` | {f.size} | `{name}` | {', '.join(s.missing())} | "
            f"{'yes' if f.plate else 'no'} | {page_name} | {', '.join(sorted(citation.pages))} |"
        )
    return "\n".join(lines) + "\n"
