# SPDX-License-Identifier: GPL-3.0-or-later
"""Render the game reference lists as Markdown pages: docs/references/index.md and one page per topic.

Every entry gets a stable anchor, `<topic anchor>-<key>` (`characters.md#char-32`), so other pages, issues and mods
can link to it. The pages are generated: `coney-tools refs render` rewrites them and `--check` fails when one is out
of date with its YAML.

Research: docs/guides/research-workflow.md#reference-lists
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from typing import Any

from coney_tools.refs import Field, RefList, Topic

GENERATED = "<!-- Generated by `coney-tools refs render` from research/references/{key}.yaml. Do not edit. -->"
IMAGE_WIDTH = 96  # pixels: the thumbnails are 256 x 256, shown small in tables


def slug(value: Any) -> str:
    """An anchor-safe form of a key: lower case, runs of other characters as one `-`."""
    text = f"{value:08x}" if isinstance(value, int) and value > 0xFFFF else str(value)
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "x"


def anchor(topic: Topic, key: Any) -> str:
    """The anchor of an entry: `<prefix>-<slug(key)>`."""
    return f"{topic.anchor}-{slug(key)}"


def _escape(text: str) -> str:
    """Make prose safe inside a table cell: no pipes or line breaks."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _code(text: str) -> str:
    """A name as inline code (backticks inside are rare; a double fence handles them)."""
    text = text.replace("|", "\\|")
    return f"`` {text} ``" if "`" in text else f"`{text}`"


def _number(value: float | int) -> str:
    """A number without trailing noise: ints as is, floats rounded to 4 significant decimals."""
    if isinstance(value, float):
        return f"{value:.4f}".rstrip("0").rstrip(".") if value != int(value) else str(int(value))
    return str(value)


def cell(spec: Field, value: Any, topic_key: str = "") -> str:
    """One table cell for `value` of field `spec`."""
    if value is None or value == [] or value == {}:
        return ""
    if spec.name == "image":
        return f'![{_escape(str(value))}](images/{value}){{ width="{IMAGE_WIDTH}" }}'
    if spec.name == "swatch":
        return f'<span style="display:inline-block;width:2em;height:1em;background:#{value[:6]}"></span>'
    if spec.link and isinstance(value, list):
        page, prefix = spec.link.split("#")
        return ", ".join(
            f"[{_number(v) if isinstance(v, (int, float)) else v}]({page}#{prefix}-{slug(v)})" for v in value
        )
    if spec.link:
        page, prefix = spec.link.split("#")
        return f"[{_number(value) if isinstance(value, (int, float)) else value}]({page}#{prefix}-{slug(value)})"
    if spec.kind == "hex" and isinstance(value, int):
        return _code(f"0x{value:08x}" if value > 0xFFFF else f"0x{value:04x}")
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (int, float)):
        return _number(value)
    if isinstance(value, dict):
        return ", ".join(f"{k} {_number(v) if isinstance(v, (int, float)) else v}" for k, v in value.items())
    if isinstance(value, list):
        parts = [_number(v) if isinstance(v, (int, float)) else _cell_list_item(v) for v in value]
        return ", ".join(parts)
    text = str(value)
    return _escape(text) if spec.curated or spec.prose else _code(text)


def _cell_list_item(value: Any) -> str:
    """One item of a list cell: names as code, nested lists in braces."""
    if isinstance(value, list):
        return "{" + ", ".join(_number(v) if isinstance(v, (int, float)) else str(v) for v in value) + "}"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k} {v}" for k, v in value.items()) + "}"
    return _code(str(value))


def _columns(topic: Topic, entries: Sequence[dict[str, Any]]) -> list[Field]:
    """The fields shown as columns: those with a heading that at least one entry fills."""
    shown = []
    for spec in topic.field_map().values():
        if spec.column is None or spec.name == topic.group_by:
            continue
        if spec.name == topic.key_field or any(entry.get(spec.name) not in (None, [], {}) for entry in entries):
            shown.append(spec)
    # The thumbnail goes right after the first column: these tables are wider than the page, so a picture in the last
    # column would only show after scrolling sideways. The first column keeps the row's anchor.
    images = [spec for spec in shown if spec.name == "image"]
    rest = [spec for spec in shown if spec.name != "image"]
    return rest[:1] + images + rest[1:]


def table(topic: Topic, entries: Sequence[dict[str, Any]]) -> list[str]:
    """A Markdown table of `entries`, the first cell of each row carrying the entry's anchor."""
    columns = _columns(topic, entries)
    lines = ["| " + " | ".join(spec.column or spec.name for spec in columns) + " |"]
    lines.append("| " + " | ".join("---" for _ in columns) + " |")
    for entry in entries:
        cells = [cell(spec, entry.get(spec.name), topic.key) for spec in columns]
        cells[0] = f'<span id="{anchor(topic, entry.get(topic.key_field))}"></span>{cells[0]}'
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def _schema(topic: Topic) -> list[str]:
    """The topic's schema as a table: field, type, hand-written or extracted, meaning."""
    lines = ["| Field | Type | Hand-written | Meaning |", "| --- | --- | --- | --- |"]
    for spec in topic.field_map().values():
        lines.append(f"| `{spec.name}` | {spec.kind} | {'yes' if spec.curated else ''} | {_escape(spec.doc)} |")
    return lines


def _group_order(values: list[str]) -> list[str]:
    """Groups in first-seen order (the YAML's order is meaningful), unnamed ones last."""
    order: list[str] = []
    for value in values:
        if value not in order:
            order.append(value)
    return order


def page(reflist: RefList) -> str:
    """The Markdown page of one reference list."""
    topic = reflist.topic
    entries = reflist.resolved()
    lines = [f"# {reflist.title}", "", GENERATED.format(key=topic.key), ""]
    if reflist.about:
        lines += [reflist.about, ""]
    if reflist.complete:
        lines += ['!!! info "What is complete"', ""]
        lines += [("    " + line) if line else "" for line in reflist.complete.splitlines()]
        lines.append("")
    lines += [f"{len(entries):,} entries. Data: `research/references/{topic.key}.yaml`.", ""]
    if topic.group_by:
        groups = _group_order([str(entry.get(topic.group_by) or "other") for entry in entries])
        for group in groups:
            members = [entry for entry in entries if str(entry.get(topic.group_by) or "other") == group]
            lines += [f"## {group} {{#{slug(group)}}}", "", f"{len(members):,} entries.", ""]
            lines += table(topic, members)
            lines.append("")
    else:
        lines += ["## Entries", ""]
        lines += table(topic, entries)
        lines.append("")
    evidence = sorted({str(entry.get("evidence")) for entry in entries})
    sources = sorted({str(entry.get("source")) for entry in entries if entry.get("source")})
    lines += ["## Sources and evidence", ""]
    lines += [f"Evidence levels used: {', '.join(evidence)}.", ""]
    if len(sources) <= 12:
        lines += [f"- {_escape(source)}" for source in sources]
    else:
        lines.append(f"{len(sources)} distinct sources; each entry's source is in the YAML.")
    lines += ["", "## Fields", ""]
    lines += _schema(topic)
    return "\n".join(lines).rstrip() + "\n"


def index(reflists: Sequence[RefList], bindings_page: bool) -> str:
    """The index page: what the references are, the list of topics with their counts, how to contribute."""
    lines = [
        "# Game references",
        "",
        GENERATED.format(key="*"),
        "",
        "Lists of the things in *The Warriors* that scripts, mods and Coney's own code refer to: characters,",
        "gangs, objects and weapons, levels, animations, controls, colours, text tags, script constants, sounds,",
        "script events and the names of the files in the game's archive. They play the part FiveM's",
        "[game references](https://docs.fivem.net/docs/game-references/) play for GTA V: a modder looks up the id or",
        "name to pass, an implementer the value to expect.",
        "",
        '**Characters are "humans".** The game calls every person, the player included, a human: scripts create one',
        "with `HuCreate`, the engine updates them all in `Humans_Update`, and most character bindings start with `Hu`.",
        "A human is the game's equivalent of GTA's ped; see [Characters (research)](../research/characters.md).",
        "",
        "Everything here is a name, an id, a number or our own short description, read from the player's own disc by",
        "`coney-tools refs extract` and checked by hand. No game text, script source, model or image from the disc is",
        'copied ([LEGAL.md](repo:LEGAL.md#no-game-data), "Reference lists").',
        "",
        "## Lists",
        "",
        "| List | Entries | What is complete |",
        "| --- | ---: | --- |",
    ]
    for reflist in reflists:
        first = reflist.complete.split(". ")[0].rstrip(".").replace("\n", " ") if reflist.complete else ""
        lines.append(
            f"| [{reflist.topic.nav or reflist.title}]({reflist.topic.key}.md) | {len(reflist.entries):,} | "
            f"{_escape(first)}. |"
        )
    lines += ["", "## Script bindings", ""]
    if bindings_page:
        lines.append("The functions the scripts call are listed in [Script bindings](bindings/index.md).")
    else:
        lines += [
            "The functions the scripts call (956 bindings) get their own masterlist, Script bindings, in this section;",
            "until it lands, see the [roadmap](../roadmap.md#script-mods).",
        ]
    lines += [
        "",
        "## Images",
        "",
        "Characters and objects may show a thumbnail. Coney renders them itself from the player's disc",
        "(`coney --render-references DIR --names FILE`, [Building](../guides/building.md)): 256 x 256 transparent",
        "PNGs in `docs/references/images/`, named after the entry's stable reference name, so the renderer and",
        "these lists agree without a lookup table:",
        "",
        "| Lists | File name | Example |",
        "| --- | --- | --- |",
        "| Characters, Character models | `characters/<model name>.png`, or `<name hash>.png` for a model with no "
        "recovered name | `characters/warr_re_cv.png` |",
        "| Objects | `objects/<name>.png`, the object type name | `objects/dyn_bat.png` |",
        "",
        "`coney-tools refs extract` fills an entry's `image` field when its file exists; a missing image is simply",
        "left out of the table.",
        "",
        "## Contributing",
        "",
        "Edit the YAML in `research/references/`, then run `uv run --project python coney-tools refs render`. The",
        "hand-written fields (who a character is, what a constant means) are kept when the lists are refreshed from",
        "the disc with `coney-tools refs extract`. The schema and rules are in",
        "[Research workflow](../guides/research-workflow.md#reference-lists).",
    ]
    return "\n".join(lines) + "\n"
